src/ebay-listbox-button/__tests__/index.spec.tsx
src/ebay-listbox-button/listbox-button.tsx

Old default 
setTimeout(() => optionsContainerRef.current.focus(), 0)
https://user-images.githubusercontent.com/8145951/176749394-85dbf522-9fa4-4a99-9f2e-5c7ec0b90654.mov
May want add preventScroll Param
New 
setTimeout(() => optionsContainerRef.current.focus({ preventScroll: true }), 0)
https://user-images.githubusercontent.com/8145951/176749418-cf2c426d-12c1-4597-88c5-af8682ed1749.mov

fix(ListboxButton): page scrolls up to the top when the user clicks on listbox-button #4

---

.storybook/preview-head.html
.storybook/preview.js
README.md
package.json
src/ebay-badge/README.md
src/ebay-breadcrumbs/README.md
src/ebay-button/README.md
src/ebay-checkbox/README.md
src/ebay-cta-button/README.md
src/ebay-drawer-dialog/README.md
src/ebay-expand-button/README.md
src/ebay-field/README.md
src/ebay-floating-label/README.md
src/ebay-icon-button/README.md
src/ebay-infotip/README.md
src/ebay-inline-notice/README.md
src/ebay-legacy-floating-label/README.md
src/ebay-legacy-floating-label/__tests__/index.stories.tsx
src/ebay-listbox-button/README.md
src/ebay-page-notice/README.md
src/ebay-radio/README.md
src/ebay-section-notice/README.md
src/ebay-select/README.md
src/ebay-signal/README.md
src/ebay-switch/README.md
src/ebay-tooltip/README.md
yarn.lock

This will close issue #8 
The focus is to quickly support application upgrade to Skin v14:
- Update dependency to Skin v14
* Remove resolutions from `package.json` since we will only use the latest Skin
- Fix storybook and make it runnable with Skin v14
* Remove the part which force Market Sans loading. This is not necessary anymore since `import "@ebay/skin"` on storybook will include Market Sans
- Update README and component docs
* Update CSS import path accordingly.
* Remove LESS import directly from Skin `src`. This is to reduce maintenance efforts on our side when Skin source structure changes a lot.
The followings are not covered by this PR and will be tackled by separated PRs
- Update component API accordingly to eBay UI Core v9. There are a few breaking changes on their API …

Skin 14 Upgrade

---

.github/actions/analyze/action.yml
.github/actions/build/action.yml
.github/actions/release/action.yml
.github/actions/setup-node/action.yml
.github/actions/storybook/action.yml
.github/actions/test/action.yml
.github/workflows/pr.yml
.github/workflows/push.yml

- Use yarn cache instead of caching `node_modules`. There is a [suggestion](https://github.com/actions/cache/blob/main/examples.md#node---npm) to not cache node_modules folder
- Move node setup to a separate action so can be re-used
- Use `uses: actions/checkout@v3` only on workflow setup

ci: remove cache and move setup node action

---

src/common/tooltip-utils/use-tooltip.ts
src/ebay-infotip/__tests__/index.spec.tsx
src/ebay-infotip/ebay-infotip.tsx

- Add a `hostRef` on `useTooltip` and focus on it on collapse
Fix #67

FIX: EbayInfotip focus host on closing infotip

---

src/ebay-tabs/__tests__/__snapshots__/index.spec.tsx.snap
src/ebay-tabs/__tests__/index.stories.tsx
src/ebay-tabs/tab-panel.tsx
src/ebay-tabs/tab.tsx
src/ebay-tabs/tabs.tsx

This PR will fix issue #72 (when there are more than 1 ebay-tabs on a page, the page will get accessibility error due to duplicated IDs). The solution is to support prop `id` on EbayTab which will be used to generate IDs for the nesting components (tab headers and tab panels).
Others:
- Remove disable info on EbayTabs Storybook as we don't use Storybook info addons anymore.
- Add new storybook with multiple tabs
NOTE: This is a quick fix since I did not have time to refactor the component into React hooks nor updating its storybook to use CSF format.

FIX: EbayTabs duplicated ids

---

package.json
src/ebay-alert-dialog/__tests__/__snapshots__/index.spec.tsx.snap
src/ebay-confirm-dialog/__tests__/__snapshots__/index.spec.tsx.snap
src/ebay-dialog-base/dialog-base-with-state.tsx
src/ebay-drawer-dialog/__tests__/__snapshots__/index.spec.tsx.snap
src/ebay-fullscreen-dialog/__tests__/__snapshots__/index.spec.tsx.snap
src/ebay-lightbox-dialog/__tests__/__snapshots__/index.spec.tsx.snap
src/ebay-panel-dialog/__tests__/__snapshots__/index.spec.tsx.snap
yarn.lock

Remove react focus lock which was removed on [a PR to fix dialog animation issue](https://github.corp.ebay.com/React/ebayui-core-react/pull/453) but accidentally [brought back on the PR to fix toast dialog accessibility issue](https://github.corp.ebay.com/React/ebayui-core-react/pull/391/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R63).
- The dialog focus trap should be handle by makeup-keyboard-trap
- This PR potentially could fix the focus issue of a dialog with a text input (the focus stays inside the input text even if user clicks on the dialog area).

FIX: Remove react-focus-lock

---

src/ebay-checkbox/__tests__/__snapshots__/index.spec.tsx.snap
src/ebay-icon-button/__tests__/__snapshots__/index.spec.tsx.snap
src/ebay-icon/__tests__/__snapshots__/index.spec.tsx.snap
src/ebay-icon/icon.tsx
src/ebay-infotip/__tests__/__snapshots__/index.spec.tsx.snap
src/ebay-menu/__tests__/__snapshots__/index.spec.tsx.snap
src/ebay-radio/__tests__/__snapshots__/index.spec.tsx.snap

The EbayIcon does not properly render SVG width and height attributes. It should generate the default SVG width & height based on icon suffix name (e.g `small`, `large`) but it did not work and always fallback to the default size 24px (see [EbayIcon snapshot](https://github.com/eBay/ebayui-core-react/blob/1.4.2/src/ebay-icon/__tests__/__snapshots__/index.spec.tsx.snap#L31-L38) for an example)
```jsx
<EbayIcon name="addSmall" />
// OUTPUT
<svg
class="icon icon--add-small"
height="24px"  // EXPECTED: should be 16px
width="24px"  // EXPECTED: should be 16px
// ...
/>
<EbayIcon name="bankLarge" />
// OUTPUT
<svg
class="icon icon--bank-large"
height="24px"  // EXPECTED: should be 64px
width="24px"  // EXPECTED: should be 64px
// ...
/>
```
EbayIcon check the given icon name and get the size …

FIX: ebay-icon generates incorrect SVG width & height values

---

src/ebay-inline-notice/__tests__/__snapshots__/index.spec.tsx.snap
src/ebay-inline-notice/inline-notice.tsx
src/ebay-page-notice/__tests__/__snapshots__/index.spec.tsx.snap
src/ebay-page-notice/page-notice.tsx
src/ebay-section-notice/__tests__/__snapshots__/index.spec.tsx.snap
src/ebay-section-notice/section-notice.tsx

This will fix issue #77 , which will make the icon smaller on page notice, section notice, and inline notice, based on the Skin v14.12.0 changes.

MINOR: Update icon on page, section, & inline notice

---

src/ebay-section-notice/__tests__/__snapshots__/index.spec.tsx.snap
src/ebay-section-notice/__tests__/index.stories.tsx

All buttons and links should look like links and not buttons (like it was before).
Storybook:
https://opensource.ebay.com/ebayui-core-react/feat/section-notice/index.html?path=/story/ebay-section-notice--default-message-with-action

EbaySectionNotice: Update stories

---

src/ebay-page-notice/page-notice.tsx

The a11yDismissText attributes should have been optional, but it wasn't, which would cause issues if you were using strict typescript.

Make the page notice  a11yDismissText attribute optional

---

src/ebay-page-notice/__tests__/__snapshots__/index.spec.tsx.snap
src/ebay-page-notice/__tests__/index.stories.tsx

Many of the page-notice examples were using strong tags for a header instead of using EbayPageNoticeTitle. Updated these stories and their snapshots.
fixes https://github.com/eBay/ebayui-core-react/issues/91
This time without all the extra stuff that came along when the branch was changed to 2.0.0.

Issue 91: Update Page Notice stories to use EbayPageNoticeTitle #118

---

src/ebay-drawer-dialog/__tests__/__snapshots__/index.spec.tsx.snap
src/ebay-drawer-dialog/components/drawer.tsx

Button without a type defaults to a "submit" action. If this drawer is hosted inside a form, it will submit the form instead of expanding. By setting the type to "button" we prevent that functionality.

FIX: Adding "button" type to button

---

src/ebay-drawer-dialog/README.md
src/ebay-drawer-dialog/__tests__/__snapshots__/index.spec.tsx.snap
src/ebay-drawer-dialog/__tests__/index.stories.tsx
src/ebay-drawer-dialog/components/drawer.tsx

fixed #54 
updated stories and readme
storybook: https://opensource.ebay.com/ebayui-core-react/fix/drawer-expandable/index.html?path=/story/ebay-drawer-dialog--trigger-expanded

[#54] EbayDrawer: make `expandable` a controlled prop

---

src/ebay-button/__tests__/__snapshots__/index.spec.tsx.snap
src/ebay-button/__tests__/index.stories.tsx
src/ebay-button/button-expand.tsx
src/ebay-button/button.tsx

fixes #155 
- fixed use-case [icon-only](https://opensource.ebay.com/ebayui-core-react/fix-EbayButton/index.html?path=/story/ebay-button--icon-only)
- added use-case [with-icon](https://opensource.ebay.com/ebayui-core-react/fix-EbayButton/index.html?path=/story/ebay-button--with-icon)
- fixed [truncated story](https://opensource.ebay.com/ebayui-core-react/fix-EbayButton/index.html?path=/story/ebay-button--truncated)
- added more [loading button examples](https://opensource.ebay.com/ebayui-core-react/fix-EbayButton/index.html?path=/story/ebay-button--loading-button) and found a [skin bug](https://github.com/eBay/skin/issues/1940)

(fix) EbayButton: fix icon and expand use cases

---

src/ebay-infotip/README.md
src/ebay-infotip/__tests__/__snapshots__/index.spec.tsx.snap
src/ebay-infotip/__tests__/index.stories.tsx
src/ebay-infotip/ebay-infotip.tsx

Latest skin versions changed to use a drawer dialog instead of lightbox dialog on infotip, this PR change this behavior and also fix the title to rendered in the right place of the dialog.
Also, updated EbayInfotip docs
Storybook: https://opensource.ebay.com/ebayui-core-react/hlimas/infotip-modal-style/index.html?path=/story/ebay-infotip--modal

FEAT: Use DrawerDialog on EbayInfotip as per skin spec

---

src/ebay-button/README.md
src/ebay-button/__tests__/__snapshots__/index.spec.tsx.snap
src/ebay-button/__tests__/index.stories.tsx
src/ebay-button/button-expand.tsx
src/ebay-button/button.tsx
src/ebay-button/types.ts
src/ebay-fake-menu-button/__tests__/__snapshots__/index.spec.tsx.snap

- Add `split` prop (will be used by EbaySplitButton component)
- Improve expand-button feature, add more stories
- Improve readme
Storybook: https://opensource.ebay.com/ebayui-core-react/ebay-button-split/index.html?path=/story/ebay-button--split-button

EbayButton: add `split` prop

---

src/ebay-page-notice/README.md
src/ebay-page-notice/__tests__/__snapshots__/index.spec.tsx.snap
src/ebay-page-notice/__tests__/index.stories.tsx
src/ebay-page-notice/page-notice.tsx

Moved to branch instead of fork.
Accessibility Team filed a bug for the below issue.
> **Expected Result**
The value assigned to an id attribute used in ARIA or in form labels must be unique to prevent the second instance from being overlooked by assistive technology.
> **Actual Result**
Document has multiple elements referenced with ARIA with the same id attribute: attention-status
Some eBay applications use multiple of these EbayPageNotice with the same status, so the ids end up being the same. So, to fix this without breaking other applications, I added an optional override to that key.

Added id prop to EbayPageNotice

---

src/ebay-pagination/pagination-item.tsx
src/ebay-pagination/pagination.tsx

- Fix on dots not clickable for "show-last" variation
Storybook: https://opensource.ebay.com/ebayui-core-react/pagination-clickable-overflow-fix/index.html?path=/story/ebay-pagination--variant-showlast-interactive

[Fix] Pagination show-last variant overflow button click disabled

---

src/common/event-utils/index.ts
src/common/event-utils/types.ts
src/ebay-menu/README.md
src/ebay-menu/__tests__/__snapshots__/index.spec.tsx.snap
src/ebay-menu/__tests__/index.spec.tsx
src/ebay-menu/__tests__/index.stories.tsx
src/ebay-menu/index.ts
src/ebay-menu/menu-item.tsx
src/ebay-menu/menu.tsx
src/ebay-menu/types.ts
src/ebay-tabs/tabs.tsx
src/index.ts

- Implements #171 for EbayMenu
- Add callback tests
- Add story actions to see those callbacks
- Follow marko API
I'm making this PR against `improved-callbacks` branch, cause those callbacks are incompatible with old ones and will break the code that uses them. We'll bump major version when we merge that branch.
storybook: https://opensource.ebay.com/ebayui-core-react/EbayMenu-callbacks/index.html?path=/story/ebay-menu--default

EbayMenu: Improve callbacks

---

src/common/tooltip-utils/constants.ts
src/common/tooltip-utils/tooltip-content.tsx
src/ebay-infotip/__tests__/__snapshots__/index.spec.tsx.snap
src/ebay-section-title/__tests__/__snapshots__/index.spec.tsx.snap
src/ebay-tourtip/__tests__/__snapshots__/index.spec.tsx.snap

Following Marko [implementation](https://github.com/eBay/ebayui-core/blob/master/src/components/components/ebay-tooltip-overlay/index.marko#L28)
- infotip -> remove `role`
- tooltip -> role="tooltip"
- tourtip -> role="region"
Fixes #208

FIX: Remove tooltip role from infotip

---

src/ebay-dialog-base/components/dialogBase.tsx
src/ebay-drawer-dialog/__tests__/__snapshots__/index.spec.tsx.snap
src/ebay-drawer-dialog/__tests__/index.spec.tsx
src/ebay-drawer-dialog/__tests__/index.stories.tsx
src/ebay-drawer-dialog/components/drawer.tsx

Change:
This PR adds a check to hide the close button on drawer-dialog ( `X`  button ) when `noHandle` attribute is set to true.

Add buttonPosition attribute check for close icon-button - Dialog

---

src/ebay-inline-notice/__tests__/__snapshots__/index.spec.tsx.snap
src/ebay-inline-notice/inline-notice.tsx

Updated the icon names to reflect the changes in skin 16.

[#221] Icons do not render for inline-notice

---

src/ebay-infotip/__tests__/__snapshots__/index.spec.tsx.snap
src/ebay-infotip/ebay-infotip.tsx

Fixed outdated icon name.
Storybook:
https://opensource.ebay.com/ebayui-core-react/fix-intotip-icon/index.html?path=/story/ebay-infotip--default

Fix EbayInfotip icon name

---

src/common/tooltip-utils/tooltip.tsx
src/ebay-infotip/__tests__/__snapshots__/index.spec.tsx.snap
src/ebay-infotip/ebay-infotip.tsx

Fixes #238 
- Move the drawer dialog as a sibling of the infotip in that way styles are not conflicting between infotip and drawer styles

FIX: EbayInfotip - move drawer as a sibling of the infotip

---

src/ebay-carousel/__tests__/__snapshots__/index.spec.tsx.snap
src/ebay-carousel/carousel-control-button.tsx

- Use chevron 12 instead of 24 as per skin

FIX: Update carousel control icons with latest skin guidelines

---

src/ebay-listbox-button/__tests__/index.spec.tsx
src/ebay-listbox-button/listbox-button.tsx

Changed to use `index` from the onChange callback instead of variable state `selectedIndex`, since the state variable is not updated yet.

FIX: ListboxButton - use most recent index instead of state variable

---

src/ebay-listbox-button/README.md
src/ebay-listbox-button/__tests__/__snapshots__/index.spec.tsx.snap
src/ebay-listbox-button/__tests__/index.spec.tsx
src/ebay-listbox-button/__tests__/index.stories.tsx
src/ebay-listbox-button/listbox-button.tsx

`unselectedText` - The text to be shown when no options are selected. Default is '-'. Cannot be used with floating-label [storybook case](https://opensource.ebay.com/ebayui-core-react/listbox-button-props/index.html?path=/story/ebay-listbox-button--default-no-selected-option)
`prefixLabel` - The label to add before each selected item on the button. Cannot be used with prefix-id [storybook case](https://opensource.ebay.com/ebayui-core-react/listbox-button-props/index.html?path=/story/ebay-listbox-button--prefix-label)
`selected` - allows you to set the selected index option to selected [storybook case](https://opensource.ebay.com/ebayui-core-react/listbox-button-props/index.html?path=/story/ebay-listbox-button--preselected-index)

EbayListboxButton: Support missing props [FEAT] [#256]

---

src/common/floating-label-utils/hooks.tsx
src/ebay-textbox/__tests__/__snapshots__/index.spec.tsx.snap
src/ebay-textbox/__tests__/index.stories.tsx
src/ebay-textbox/textbox.tsx

- Disable inline animation for type date since it was overlapping with the placeholder and also on safari the value overlaps in some cases

FIX: Disable floating label for date types

---

src/ebay-listbox-button/__tests__/__snapshots__/index.spec.tsx.snap
src/ebay-listbox-button/listbox-button.tsx

This is a suggestion on a better way of fixing the warning problem with the hidden controlled select.
Another solution is just to have the onChange with a function that does nothing, but I'd say it's better to just keep the same behaviour as the main select.

Fix EbayListboxButton console warning

---

src/ebay-tourtip/ebay-tourtip.tsx

There is currently a console error when using Tourtips. It's due to the wrong naming for aria attributes. According to React's documentation, aria attributes should not be camel case (https://react.dev/reference/react-dom/components/common#common-props)
Screenshots
Error:
Fix:

FIX: Use correct aria attribute names in Tourtip

---

src/ebay-section-notice/README.md
src/ebay-section-notice/__tests__/__snapshots__/index.spec.tsx.snap
src/ebay-section-notice/__tests__/index.stories.tsx
src/ebay-section-notice/section-notice.tsx

- Add `education` section notice
- Add `prominent`, `iconClass` and `educationIcon` property on section-notice

FEAT: Add support for education section notice

---

src/ebay-listbox-button/listbox-button.tsx

This fixes accessibility issue when no option is selected and up and down arrows are used

Fixed key up and down use with no selection

---

src/ebay-switch/__tests__/__snapshots__/index.spec.tsx.snap
src/ebay-switch/__tests__/index.spec.tsx
src/ebay-switch/__tests__/index.stories.tsx
src/ebay-switch/ebay-switch.tsx

This PR addresses https://github.com/eBay/ebayui-core-react/issues/296. It doesn't seem like I have permissions to directly link issue.
This change allows `EbaySwitch` to be controlled by `checked` prop.
- Added similar `isControlled` logic from `EbayCheckbox` into `EbaySwitch`.
- Added `defaultChecked` prop to follow logic from `EbayCheckbox`.
- Added unit test to verify checkbox is not changed.
- Added story that changes `checked` prop.
Showing issue before and updated stories after:
https://github.com/eBay/ebayui-core-react/assets/3955187/9d0658f3-1697-4d99-96c6-210b21b38c58

fix: added controlled logic for switch

---

src/ebay-select/ebay-select.tsx

Adding the support of the HOC `withForwardedRef` to `EbaySelect` component

Adding withForwardedRef HOC to EbaySelect

---

src/ebay-listbox-button/README.md
src/ebay-select/README.md
src/ebay-textbox/README.md

Updated documentation to include the necessary CSS for proper functioning of floating labels.
When utilizing the `ebay-textbox` element alongside floating labels, it didn't function as expected. The solution was to include the floating-label CSS file, which resolved the issue.
I presume the same applies to `ebay-listbox-button` and `ebay-select` elements, although I have **not** tested it.

Update docs: Add reference to floating labels CSS

---

src/ebay-dialog-base/__tests__/index.spec.tsx
src/ebay-dialog-base/components/dialogBase.tsx

Issue related to react `18.2.0` witch will cause `baseDialog` to invoke `useEffect` when updating state for the content inside dialog.  It may happen that attach document click will happen after call cleanup inside useEffect.
Fix: clean timeout each time when useEffect cals cleanup.

fix: dialog document attach event timeout

---

src/ebay-calendar/__tests__/render.spec.tsx
src/ebay-fullscreen-dialog/fullscreen-dialog.tsx

Moving the close button to the right for the full screen modal to match the Marko component. 
Also need to fix one of the tests in Calendar so my PR would pass.

#339: Full screen modal: Close button in wrong location

---

src/ebay-icon/icon.tsx
src/ebay-page-notice/__tests__/__snapshots__/render.spec.tsx.snap
src/ebay-progress-spinner/progress-spinner.tsx

- Use spinner20, spinner24, spinner30 icons on progressive-spinner depending on the size
- Add icon name in the class for filled icons

fix(Icon): Use proper icon on spinner and icon class for filled icons

---

src/ebay-drawer-dialog/__tests__/index.spec.tsx
src/ebay-drawer-dialog/components/drawer.tsx

Currently the `windowClass` prop is swallowed by the drawer component and not being passed to the DialogBase. This PR fixes that.

fix: fixed drawer windowClass prop

---

src/ebay-icon-button/README.md

Without importing `@ebay/skin/icon`:
With importing it:

fix ebay-icon-button docs to include importing `@ebay/skin/icon` CSS

---

src/ebay-checkbox/README.md

- Adding instructions to include `EbaySvg` at root level layout component when using EbayCheckbox component.
**Before**
**After**

Adding instructions to import EbaySvg when rendering checkbox

---

src/ebay-section-notice/__tests__/index.spec.tsx
src/ebay-section-notice/section-notice.tsx

Generate the same id section-notice-information when there are multiple SectionNotices causing invalid HTML and  duplicate-id-aria on accessibility tools

support unique ids on ebay-section

---

package.json
vite.config.mjs

Rename files to be `/<component-name>/index.js` instead of `/<component-name>.js` so it maintains typescript definition files
The current `dist` folder structure is:
```
/dist
/ebay-button
/index.d.ts
ebay-button.js
```
This is causing an issue when imported internally (for example the `ebay-dialog-base`) where typescript is conflicting with which file to solve (is it `root/name/index.d.ts` or is it `root/name.js`).

fix: TypeScript module resolution

---

.storybook/preview.jsx
src/ebay-dialog-base/components/animation.ts

- Change to use a previousOpen value to make sure we show the hide animation only when it changes.
- Add StrictMode to storybook
The previous logic was checking if it was the first render, but on StrictMode the layout effect is executed twice, triggering the hide animation logic during development.

fix(DialogBase): Don't trigger the hide animation on strict mode

---

src/ebay-svg/svg.tsx

Currently screen readers are announcing the SVG icon definitions when hitting the page. This PR is to hide them from screen readers

fix(EbaySvg): Hide SVG definition from screen readers

---

src/ebay-listbox-button/__tests__/index.spec.tsx
src/ebay-listbox-button/listbox-button-option.tsx
src/ebay-listbox-button/listbox-button.tsx

- Show the `listbox` on focus of the button since on click the screen reader cannot check for it on focus
- Update `aria-activedescendent` logic to render function instead of manually setting the attributes of the ref
- Move `aria-activedescendent` to `listbox` component instead of div container

fix(EbayListboxButton): Show listbox with active descendent on button focus

---

.changeset/thin-ducks-develop.md
src/ebay-carousel/__tests__/__snapshots__/index.spec.tsx.snap
src/ebay-carousel/carousel-control-button.tsx

- Change arrow icons size from 12 to 16

fix(EbayCarousel): Update icon size to 16

---

.changeset/late-shoes-divide.md
.github/workflows/pr.yml

- Check that the owner pull request repository is the same as the origin
Tested in this fork PR build (skip deploy): https://github.com/eBay/ebayui-core-react/actions/runs/12837673345
And this PR branch (deploy): https://github.com/eBay/ebayui-core-react/actions/runs/12837717464?pr=404

core: fix fork GH action deploy condition

---

.changeset/wicked-wasps-rush.md
src/ebay-lightbox-dialog/README.md
src/ebay-lightbox-dialog/__tests__/index.stories.tsx
src/ebay-lightbox-dialog/__tests__/render.spec.tsx
src/ebay-lightbox-dialog/lightbox-dialog.tsx

- Add `bannerImgSrc`, `bannerImgPositition` new attributes
- Add types on stories and remove `_` from the name
- Add stories controls on lightbox dialog
- Remove unnecessary `classPrefix` variable for better reading and understanding of the skin class name usage

feat(EbayLightboxDialog): add support for banner image

---

.changeset/metal-monkeys-tap.md
package.json
vite.config.mjs
yarn.lock

Fixes #420 
Previously it bundle like this:
```js
U = require("makeup-expander")
new U()
```
Now is:
```js
c = require("makeup-expander")
const { default: K = c } = c // some other null checks also
new K()
```

fix: use cjs interop to properly bundle makeup-js packages inside vite

---

.changeset/honest-parents-remember.md
src/ebay-fake-menu-button/menu-button.tsx

`FakeMenuButton` and `MenuButton` have a different HTML structure, here we are putting the `btn-cell` back as it was before  for fake menu button
https://opensource.ebay.com/ebayui-core-react/fix-fake-menu-button/index.html?path=/story/buttons-ebay-fake-menu-button--default

fix(EbayFakeMenuButton): use btn-cell to add margin between chevron and action content

---

.changeset/neat-suns-explode.md
tsconfig.json

nullish coalescing (`??`) is not supported on Webpack 4, updating the typescript target so it supported accross different builders.

fix: use target es2015 instead of esnext for better compatibility

---

.changeset/proud-games-float.md
.storybook/preview.jsx
src/ebay-checkbox/README.md
src/ebay-checkbox/checkbox.tsx
src/ebay-checkbox/index.ts
src/ebay-checkbox/types.ts
src/ebay-field/README.md
src/ebay-table/README.md
src/ebay-table/__tests__/__snapshots__/render.spec.tsx.snap
src/ebay-table/__tests__/data.json
src/ebay-table/__tests__/index.spec.tsx
src/ebay-table/__tests__/index.stories.tsx
src/ebay-table/__tests__/render.spec.tsx
src/ebay-table/index.ts
src/ebay-table/table-cell.tsx
src/ebay-table/table-header.tsx
src/ebay-table/table-row.tsx
src/ebay-table/table.tsx
src/ebay-table/types.ts
src/ebay-tri-state-checkbox/Readme.md
src/ebay-tri-state-checkbox/index.ts
src/ebay-tri-state-checkbox/tri-state-checkbox.tsx
src/ebay-tri-state-checkbox/types.ts

- Add new `EbayTable` component
- Fix tri-state-checkbox `aria-checked` correct value for controlled components
- Add types for `EbayCheckbox` and `EbayTriStateCheckbox` handlers
- Add icons information on `EbayCheckbox` and `EbayTriStateCheckbox` documentation
Storybook: https://opensource.ebay.com/ebayui-core-react/table/?path=/docs/data-display-ebay-table--docs

feat(EbayTable): add new table component

---

.changeset/pink-waves-repair.md
vite.config.mjs

In some bundles this is causing `E is not a constructor`

fix: add all makeup libraries to cjsInterop plugin

---

.changeset/fast-seas-kick.md
package.json
src/common/floating-label-utils/hooks.tsx
src/ebay-select/__tests__/render.spec.tsx

- Remove `floating-label__label--inline` from our side as it is handle by makeup-floating-label

fix(Select): remove floating-label--inline class on first render

---

.changeset/giant-crabs-prove.md
src/ebay-fake-link/README.md
src/ebay-fake-link/__tests__/__snapshots__/render.spec.tsx.snap
src/ebay-fake-link/__tests__/index.spec.tsx
src/ebay-fake-link/__tests__/index.stories.tsx
src/ebay-fake-link/__tests__/render.spec.tsx
src/ebay-fake-link/fake-link.tsx
src/ebay-fake-link/index.ts

Marko: https://github.com/eBay/ebayui-core/tree/master/src/components/ebay-fake-link
Storybook: https://opensource.ebay.com/ebayui-core-react/fake-link/?path=/docs/buttons-ebay-fake-link--docs
Note: `standalone` variant currently don't have any behavior change, it should be fixed on skin
Fixes #274

feat: Add new EbayFakeLink component
