eBay/ebayui-core-react

.husky/pre-commit, .husky/pre-push, package.json, yarn.lock
- Update husky to latest version using [husky-4-to-8](https://github.com/typicode/husky-4-to-8) script
- Add `yarn build` as part of pre-push
=> chore: Upgrade husky version

package.json, src/common/event-utils/__tests__/use-key-press.spec.tsx, src/common/event-utils/__tests__/use-roving-index.spec.tsx, yarn.lock
=> FIX Use React 16 as a dev dependency for typing issues

src/ebay-icon/README.md, src/ebay-icon/__tests__/__snapshots__/index.spec.tsx.snap, src/ebay-icon/__tests__/index.stories.tsx, src/ebay-icon/icon.tsx
new type prop 
`type` | String | No | no | 'icon' or 'program-badge'  default 'icon'
=> FEAT: Program badges icons

src/ebay-tabs/__tests__/__snapshots__/index.spec.tsx.snap, src/ebay-tabs/__tests__/index.spec.tsx, src/ebay-tabs/__tests__/index.stories.tsx, src/ebay-tabs/tabs.tsx
Also fixes https://github.com/eBay/ebayui-core-react/pull/78
[Storybook with example](https://opensource.ebay.com/ebayui-core-react/tabs-hooks/index.html?path=/story/ebay-tab--tabs-with-inputs)
=> Convert EbayTabs to hooks

src/ebay-select/__tests__/index.stories.tsx, src/ebay-select/ebay-select.tsx
=> [#75] Fix broken definition

src/ebay-checkbox/__tests__/index.stories.tsx, src/ebay-checkbox/checkbox.tsx
=> [#76] Fix broken definition

src/ebay-checkbox/checkbox.tsx
Needed to set focus on checkbox, allows passing refs down.
=> Update Checkbox component to support refs

src/ebay-alert-dialog/__tests__/__snapshots__/index.spec.tsx.snap, src/ebay-confirm-dialog/__tests__/__snapshots__/index.spec.tsx.snap, src/ebay-confirm-dialog/__tests__/index.spec.tsx, src/ebay-dialog-base/__tests__/index.spec.tsx, src/ebay-dialog-base/dialog-base-with-state.tsx, src/ebay-drawer-dialog/__tests__/__snapshots__/index.spec.tsx.snap, src/ebay-fullscreen-dialog/__tests__/__snapshots__/index.spec.tsx.snap, src/ebay-fullscreen-dialog/__tests__/index.spec.tsx, src/ebay-infotip/__tests__/__snapshots__/index.spec.tsx.snap, src/ebay-infotip/__tests__/index.spec.tsx, src/ebay-lightbox-dialog/__tests__/__snapshots__/index.spec.tsx.snap, src/ebay-lightbox-dialog/__tests__/index.spec.tsx, src/ebay-pagination/__tests__/__snapshots__/index.spec.tsx.snap, src/ebay-pagination/__tests__/index.spec.tsx, src/ebay-panel-dialog/__tests__/__snapshots__/index.spec.tsx.snap, src/ebay-panel-dialog/__tests__/index.spec.tsx, src/ebay-toast-dialog/__tests__/__snapshots__/index.spec.tsx.snap
=> Set animated by default for Dialog

src/ebay-progress-stepper/README.md, src/ebay-progress-stepper/__tests__/__snapshots__/index.spec.tsx.snap, src/ebay-progress-stepper/__tests__/index.stories.tsx, src/ebay-progress-stepper/ebay-progress-step.tsx, src/ebay-progress-stepper/ebay-progress-stepper.tsx, src/ebay-progress-stepper/index.ts, src/ebay-progress-stepper/types.ts, src/index.ts
Storybook: https://opensource.ebay.com/ebayui-core-react/feat/progress-stepper/index.html?path=/story/ebay-progress-stepper--default
=> EbayProgressStepper: skin15

src/common/tooltip-utils/constants.ts, src/ebay-infotip/__tests__/__snapshots__/index.spec.tsx.snap, src/ebay-section-title/__tests__/__snapshots__/index.spec.tsx.snap, src/ebay-tooltip/__tests__/__snapshots__/index.spec.tsx.snap
Update style objects for different pointer types to fix alignment issues - [`<EbayInfotip />`](https://github.com/eBay/ebayui-core-react/tree/main/src/ebay-infotip)
=> FIX: Update styles for EbayInfotip pointer

src/ebay-button/README.md, src/ebay-button/__tests__/__snapshots__/index.spec.tsx.snap, src/ebay-button/__tests__/index.stories.tsx, src/ebay-button/button-text.tsx, src/ebay-button/button.tsx, src/ebay-button/types.ts
- Add new bodyState and variants for buttons
- `expand` bodyState
- `form` variant
- `borderless` attribute
=> FEAT: Add new skin button variations

src/ebay-tabs/__tests__/__snapshots__/index.spec.tsx.snap, src/ebay-tabs/__tests__/index.spec.tsx, src/ebay-tabs/__tests__/index.stories.tsx, src/ebay-tabs/tab.tsx, src/ebay-tabs/tabs.tsx
- No autofocus anymore
- Add tests for focus
- Tabs focus behaves like in Marko version
fixes #134 
storybook: https://opensource.ebay.com/ebayui-core-react/fix-tabs-autofocus/index.html?path=/story/ebay-tabs--bottom-tabs-on-long-page
=> [#134] Remove tabs autofocus

src/common/floating-label-utils/hooks.tsx, src/ebay-textbox/__tests__/__snapshots__/index.spec.tsx.snap, src/ebay-textbox/__tests__/index.stories.tsx, src/ebay-textbox/textbox.tsx
storybook: https://opensource.ebay.com/ebayui-core-react/fix-floating-label-rendering/index.html?path=/story/ebay-textbox--floating-label
=> [#98] Fix floating label rendering jump

src/ebay-icon-button/__tests__/index.spec.tsx, src/ebay-icon-button/icon-button.tsx
Just adding support for forward ref.
=> [FEAT] EbayIconButton: add forward ref

package.json, src/common/tooltip-utils/index.ts, src/common/tooltip-utils/tooltip-content.tsx, src/common/tooltip-utils/tooltip-footer.tsx, src/common/tooltip-utils/tooltip-host.tsx, src/common/tooltip-utils/tooltip.tsx, src/ebay-tourtip/README.md, src/ebay-tourtip/__tests__/__snapshots__/index.spec.tsx.snap, src/ebay-tourtip/__tests__/index.spec.tsx, src/ebay-tourtip/__tests__/index.stories.tsx, src/ebay-tourtip/ebay-tourtip-content.tsx, src/ebay-tourtip/ebay-tourtip-footer.tsx, src/ebay-tourtip/ebay-tourtip-heading.tsx, src/ebay-tourtip/ebay-tourtip-host.tsx, src/ebay-tourtip/ebay-tourtip.tsx, src/ebay-tourtip/index.ts, src/index.ts
These changes add the tourtip component with the functionality in Marko
=> Addition of tourtip component

src/common/tooltip-utils/constants.ts, src/ebay-infotip/__tests__/__snapshots__/index.spec.tsx.snap, src/ebay-section-title/__tests__/__snapshots__/index.spec.tsx.snap, src/ebay-tooltip/__tests__/__snapshots__/index.spec.tsx.snap, src/ebay-tourtip/__tests__/__snapshots__/index.spec.tsx.snap
Fixes #192
Storybook: https://opensource.ebay.com/ebayui-core-react/fix-safari-tooltip/index.html?path=/story/ebay-tooltip--pointer-direction
=> FIX: Update latest tooltip styles definition

src/ebay-video/README.md, src/ebay-video/__tests__/__snapshots__/index.spec.tsx.snap, src/ebay-video/__tests__/index.stories.tsx, src/ebay-video/const.ts, src/ebay-video/controls.tsx, src/ebay-video/shaka-player.d.ts, src/ebay-video/video.tsx
implements #188 
- add missing key attribute in sources.map
- fix `undefinedpx` when width/height props are not passed
- allow to hide report button
- show captions button instead of menu?
- get rid of `any` type
=> EbayVideo: improvements

src/ebay-button/__tests__/index.stories.tsx, src/ebay-button/button.tsx
- fixed lost event
- added some actions to storybook to make sure we support original Marko API
=> EbayButton: fix lost 'onKeydown' event

src/ebay-confirm-dialog/__tests__/index.stories.tsx, src/ebay-dialog-base/README.md, src/ebay-dialog-base/components/dialogBase.tsx, src/ebay-drawer-dialog/README.md, src/ebay-drawer-dialog/components/drawer.tsx
=> [#212, #213] Make a11y labels optional

src/ebay-video/video.tsx
=> [#225] Fix video player button

src/ebay-menu-button/__tests__/index.stories.tsx, src/ebay-menu-button/menu-button.tsx, src/ebay-menu/__tests__/index.spec.tsx, src/ebay-menu/menu.tsx, src/ebay-menu/types.ts, src/ebay-split-button/README.md, src/ebay-split-button/__tests__/__snapshots__/index.spec.tsx.snap, src/ebay-split-button/__tests__/index.spec.tsx, src/ebay-split-button/__tests__/index.stories.tsx, src/ebay-split-button/index.ts, src/ebay-split-button/split-button.tsx, src/ebay-split-button/types.ts
1. adding ebay-split-button
2. updating call back from main 
3.updating stories
=> FEAT: Adding EbaySplitButton component

src/ebay-dialog-base/README.md, src/ebay-dialog-base/__tests__/index.spec.tsx, src/ebay-dialog-base/components/dialogBase.tsx
To mirror the ebayui-core-marko dialog: https://github.com/eBay/ebayui-core/blob/master/src/components/components/ebay-dialog-base/index.marko#L54
=> feat: added a closeButtonClass prop for base dialog

src/common/floating-label-utils/hooks.tsx, src/ebay-select/__tests__/index.spec.tsx, src/ebay-textbox/__tests__/index.spec.tsx
set to false only if there is no value in element 
https://opensource.ebay.com/ebayui-core-react/main/index.html?path=/story/ebay-select--floating-label
=> fix onBlur floating label logic

package.json, src/ebay-tabs/index.ts, src/ebay-tabs/tabs.tsx, src/ebay-tabs/types.ts, yarn.lock
=> FEAT: Upgrade to TS4

src/ebay-fake-menu/README.md, src/ebay-fake-menu/__tests__/index.stories.tsx, src/ebay-fake-menu/index.ts, src/ebay-fake-menu/menu-item.tsx, src/ebay-menu/README.md, src/ebay-pagination/pagination.tsx
=> FEAT: EbayFakeMenu: support type/badgeNumber/badgeAriaLabel

src/ebay-button/__tests__/__snapshots__/index.spec.tsx.snap, src/ebay-button/__tests__/index.stories.tsx, src/ebay-button/button-expand.tsx, src/ebay-listbox-button/__tests__/__snapshots__/index.spec.tsx.snap, src/ebay-listbox-button/listbox-button.tsx, src/ebay-split-button/__tests__/__snapshots__/index.spec.tsx.snap
- Update button expand and listbox-button (other components uses a variation of these two components)
#306
=> Update chevron down to 12 instead of 16

src/ebay-button/README.md
updated docs to also point out the `tokens` dep
=> [Update] Button Docs

README.md, src/ebay-toggle-button-group/README.md, src/ebay-toggle-button-group/__tests__/__snapshots__/index.spec.tsx.snap, src/ebay-toggle-button-group/__tests__/index.spec.tsx, src/ebay-toggle-button-group/__tests__/index.stories.tsx, src/ebay-toggle-button-group/index.ts, src/ebay-toggle-button-group/toggle-button-group.tsx, src/ebay-toggle-button-group/types.ts, src/ebay-toggle-button/README.md, src/ebay-toggle-button/__tests__/__snapshots__/index.spec.tsx.snap, src/ebay-toggle-button/__tests__/index.spec.tsx, src/ebay-toggle-button/__tests__/index.stories.tsx, src/ebay-toggle-button/index.ts, src/ebay-toggle-button/toggle-button.tsx, src/ebay-toggle-button/types.ts
I can't create a new branch for this feature on the repo, so if you want me to close this and create a new PR on a new branch, please let me know.
Issue: https://github.com/eBay/ebayui-core-react/issues/281
I am working on collectibles and design asked for this component. I built for our app and I am creating a PR here with the code we have in case you want this contribution.
Heavily based on Marko's implementation:
https://github.com/eBay/ebayui-core/tree/master/src/components/ebay-toggle-button-group
https://github.com/eBay/ebayui-core/tree/master/src/components/ebay-toggle-button
If you want, I can reach me on slack in the handle bruduarte
thanks
=> FEAT: Ebay Toggle Button and Ebay Toggle Button Group

.changeset/lucky-jobs-kiss.md, config/jest/setup-tests.ts, package.json, src/ebay-listbox/README.md, src/ebay-listbox/__tests__/index.spec.tsx, src/ebay-listbox/__tests__/index.stories.tsx, src/ebay-listbox/__tests__/render.spec.tsx, src/ebay-listbox/index.ts, src/ebay-listbox/listbox-option-description.tsx, src/ebay-listbox/listbox-option.tsx, src/ebay-listbox/listbox.tsx, src/utils/index.ts, src/utils/scroll.ts, yarn.lock
- Add new `EbayListbox` component following [marko implementation](https://github.com/eBay/ebayui-core/tree/master/src/components/ebay-listbox) and API
Note: Using it on EbayListboxButton will be handle in a different PR as some changes are needed on makeup-js
Storybook link: https://opensource.ebay.com/ebayui-core-react/ebay-listbox/index.html?path=/docs/building-blocks-ebay-listbox--docs
=> feat(EbayListbox): Add new component

.changeset/poor-turkeys-itch.md, src/ebay-lightbox-dialog/__tests__/index.spec.tsx, src/ebay-lightbox-dialog/lightbox-dialog.tsx
fix top passthrough prop on light box
=> fix: top passthrough prop on light box

.changeset/mean-rats-roll.md, src/ebay-toggle-button/__tests__/__snapshots__/index.spec.tsx.snap, src/ebay-toggle-button/__tests__/index.stories.tsx, src/ebay-toggle-button/toggle-button.tsx
fix: classname passthrough prop on toggle-button
=> fix: classname passthrough prop on toggle-button

.changeset/plenty-meals-juggle.md, README.md, src/common/notice-utils/notice-footer.tsx, src/common/notice-utils/notice-title.tsx, src/ebay-education-notice/README.md, src/ebay-education-notice/__tests__/__snapshots__/index.spec.tsx.snap, src/ebay-education-notice/__tests__/__snapshots__/render.spec.tsx.snap, src/ebay-education-notice/__tests__/index.spec.tsx, src/ebay-education-notice/__tests__/index.stories.tsx, src/ebay-education-notice/__tests__/render.spec.tsx, src/ebay-education-notice/education-notice-footer.tsx, src/ebay-education-notice/education-notice-title.tsx, src/ebay-education-notice/education-notice.tsx, src/ebay-education-notice/index.ts, src/ebay-education-notice/types.ts
Issue: [#434](https://github.com/eBay/ebayui-core-react/issues/434)
Ebay Education Notice component
Demo:
https://github.com/user-attachments/assets/33662a7c-0fe2-49b6-9cbf-86ac9c550935
=> FEAT: Ebay Education Notice

.changeset/cool-mirrors-try.md, src/ebay-chip/README.md, src/ebay-chip/__tests__/index.spec.tsx, src/ebay-chip/__tests__/index.stories.tsx, src/ebay-chip/chip.tsx, src/ebay-chip/index.ts, src/ebay-chips-combobox/README.md, src/ebay-chips-combobox/__tests__/index.spec.tsx, src/ebay-chips-combobox/__tests__/index.stories.tsx, src/ebay-chips-combobox/chips-combobox.tsx, src/ebay-chips-combobox/index.ts, src/ebay-chips-combobox/types.ts, src/ebay-combobox/README.md, src/ebay-combobox/combobox.tsx
Marko: [ebay-chip](https://github.com/eBay/ebayui-core/tree/event-utils/src/components/ebay-chip) and [ebay-chips-combobox](https://github.com/eBay/ebayui-core/tree/event-utils/src/components/ebay-chips-combobox)
Storybook: 
[ebay-chip](https://opensource.ebay.com/ebayui-core-react/chips-combobox/?path=/docs/building-blocks-ebay-chip--docs)
[ebay-chips-combobox](https://opensource.ebay.com/ebayui-core-react/chips-combobox/?path=/docs/form-input-ebay-chips-combobox--docs)
Fixes #310 #426
=> feat: Add EbayChip and EbayChipsCombobox components

.changeset/famous-dragons-shake.md, package.json, src/common/dropdown.ts, src/ebay-filter-menu-button/README.md, src/ebay-filter-menu-button/__tests__/data.json, src/ebay-filter-menu-button/__tests__/index.spec.tsx, src/ebay-filter-menu-button/__tests__/index.stories.tsx, src/ebay-filter-menu-button/filter-menu-button.tsx, src/ebay-filter-menu-button/index.ts, src/ebay-filter-menu/__tests__/__snapshots__/render.spec.tsx.snap, src/ebay-filter-menu/__tests__/render.spec.tsx, src/ebay-filter-menu/filter-menu.tsx, yarn.lock
- Update FilterMenu to properly sets the tabindex
- Allow passing ref to FilterMenu
- Add new FilterMenuButton
Storybook: https://opensource.ebay.com/ebayui-core-react/filter-menu-button/?path=/docs/buttons-ebay-filter-menu-button--docs
=> feat: Add EbayFilterMenuButton component

.changeset/loud-books-jam.md, src/ebay-textbox/__tests__/__snapshots__/render.spec.tsx.snap, src/ebay-textbox/__tests__/index.stories.tsx, src/ebay-textbox/__tests__/render.spec.tsx, src/ebay-textbox/textbox.tsx
ebay-textbox with floating label fluid was not working. Fix to behave like marko's ebay-ui
=> Fix ebay-textbox floating label fluid

.changeset/eight-needles-mate.md, src/ebay-carousel/carousel.tsx, src/ebay-progress-bar-expressive/README.md, src/ebay-progress-bar-expressive/__tests__/__snapshots__/render.spec.tsx.snap, src/ebay-progress-bar-expressive/__tests__/index.spec.tsx, src/ebay-progress-bar-expressive/__tests__/index.stories.tsx, src/ebay-progress-bar-expressive/__tests__/render.spec.tsx, src/ebay-progress-bar-expressive/index.ts, src/ebay-progress-bar-expressive/progress-bar-expressive-message.tsx, src/ebay-progress-bar-expressive/progress-bar-expressive.tsx, src/utils/index.ts, src/utils/reduced-motion.ts
- Add new ProgressBarExpressive component following [marko](https://github.com/eBay/ebayui-core/tree/master/src/components/ebay-progress-bar-expressive) implementation
- Move `useReducedMotion` to a hook and re-use it in carousel and progress bar
Closes #435 
Storybook: [link](https://opensource.ebay.com/ebayui-core-react/ebay-progress-bar-expressive/index.html?path=/docs/progress-ebay-progress-bar-expressive--docs)
=> feat(ProgressBarExpressive): new component
